# Generated by Django 5.0.3 on 2024-11-12 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='publishers',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='readerlogs',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='readerlogs',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='book_id',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.authors'),
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.genres'),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.publishers'),
        ),
        migrations.AddField(
            model_name='books',
            name='reviews',
            field=models.ManyToManyField(null=True, related_name='books', to='core.reviews'),
        ),
        migrations.AddField(
            model_name='readerlogs',
            name='book',
            field=models.ManyToManyField(related_name='reader_logs', to='core.books'),
        ),
        migrations.AlterField(
            model_name='books',
            name='cover_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='info_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
