# Generated by Django 5.0.3 on 2024-11-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_authors_author_rename_books_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='reviews',
            new_name='review',
        ),
    ]
