# Generated by Django 5.0.3 on 2024-11-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_authors_book_id_remove_genres_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='reviews',
            field=models.ManyToManyField(related_name='books', to='core.reviews'),
        ),
    ]
