# Generated by Django 5.0.3 on 2024-11-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_reviews_book_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ManyToManyField(related_name='review', to='core.book'),
        ),
        migrations.AlterField(
            model_name='readerlog',
            name='book',
            field=models.ManyToManyField(related_name='reader_log', to='core.book'),
        ),
    ]
