# Generated by Django 5.0.3 on 2024-11-14 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_book_review_review_book_alter_readerlog_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readerlog',
            name='book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.AddField(
            model_name='readerlog',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader_log', to='core.book'),
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.book'),
        ),
    ]
