# Generated by Django 5.0.3 on 2024-11-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_readerlog_book_remove_review_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerlog',
            name='status',
            field=models.CharField(choices=[('TOREAD', 'To Read'), ('READING', 'Reading'), ('DNF', 'Did Not Finish'), ('SKIMMED', 'Skimmed'), ('COVER2COVER', 'Cover to Cover')], max_length=20, null=True),
        ),
    ]
