# Generated by Django 5.0.3 on 2024-11-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_book_title_alter_genre_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerlog',
            name='status',
            field=models.CharField(choices=[('TOREAD', 'To Read'), ('READING', 'Reading'), ('READ', 'Read')], max_length=20, null=True),
        ),
    ]
