# Generated by Django 5.0.3 on 2024-11-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_readerlog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(unique=True)),
                ('embedding', models.JSONField()),
            ],
        ),
    ]
