# Generated by Django 5.0.3 on 2024-12-03 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bookindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookindex',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.genre'),
        ),
    ]
