# Generated by Django 5.0.3 on 2024-12-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bookindex_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
    ]
